export function shortenText(text: string, n: number) {
    if (text.length > n) {
        return text.substring(0, n).concat("...");
    }
    return text;
}

export const genreList: { genre: string }[] = [
    { genre: "action" },
    { genre: "adventure" },
    { genre: "cars" },
    { genre: "comedy" },
    { genre: "crime" },
    { genre: "dementia" },
    { genre: "demons" },
    { genre: "drama" },
    { genre: "dub" },
    { genre: "ecchi" },
    { genre: "family" },
    { genre: "fantasy" },
    { genre: "game" },
    { genre: "gourmet" },
    { genre: "harem" },
    { genre: "historical" },
    { genre: "horror" },
    { genre: "josei" },
    { genre: "kids" },
    { genre: "magic" },
    { genre: "martial-arts" },
    { genre: "mecha" },
    { genre: "military" },
    { genre: "Mmusic" },
    { genre: "mystery" },
    { genre: "parody" },
    { genre: "police" },
    { genre: "psychological" },
    { genre: "romance" },
    { genre: "samurai" },
    { genre: "school" },
    { genre: "sci-fi" },
    { genre: "seinen" },
    { genre: "shoujo" },
    { genre: "shoujo-ai" },
    { genre: "shounen" },
    { genre: "shounen-ai" },
    { genre: "space" },
    { genre: "sports" },
    { genre: "super-power" },
    { genre: "supernatural" },
    { genre: "suspense" },
    { genre: "thriller" },
    { genre: "vampire" },
    { genre: "yaoi" },
    { genre: "yuri" },
];
